<?php

use Illuminate\Database\Seeder;

class BusinessMetasTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {


        \DB::table('business_metas')->delete();
        \DB::table('business_metas')->insert([
            [
                'business_id'        => 7,
                'business_option_id' => 10,
                'type'               => 'text',
                'key'                => 'financing_option',
                'value'              => 'option 1',
                'created_at'         => '2018-01-12 05:42:00',
                'updated_at'         => '2018-01-12 05:42:00',
            ],
            [
                'business_id'        => 12,
                'business_option_id' => 6,
                'type'               => 'file',
                'key'                => 'logo',
                'value'              => 'logo_12_5a69675c08919.jpg',
                'created_at'         => '2018-01-25 05:13:00',
                'updated_at'         => '2018-01-25 05:13:00',
            ],
            [
                'business_id'        => 12,
                'business_option_id' => 7,
                'type'               => 'text',
                'key'                => 'tagline',
                'value'              => 'tagline',
                'created_at'         => '2018-01-25 05:13:08',
                'updated_at'         => '2018-01-25 05:13:08',
            ],
            [
                'business_id'        => 12,
                'business_option_id' => 8,
                'type'               => 'text',
                'key'                => 'brand_color',
                'value'              => '#72a951',
                'created_at'         => '2018-01-25 05:13:14',
                'updated_at'         => '2018-01-25 05:13:14',
            ],
            [
                'business_id'        => 13,
                'business_option_id' => 6,
                'type'               => 'file',
                'key'                => 'logo',
                'value'              => 'logo_13_5a6967e223d86.jpg',
                'created_at'         => '2018-01-25 05:15:14',
                'updated_at'         => '2018-01-25 05:15:14',
            ],
            [
                'business_id'        => 13,
                'business_option_id' => 7,
                'type'               => 'text',
                'key'                => 'tagline',
                'value'              => 'tagline',
                'created_at'         => '2018-01-25 05:15:21',
                'updated_at'         => '2018-01-25 05:15:21',
            ],
            [
                'business_id'        => 13,
                'business_option_id' => 8,
                'type'               => 'text',
                'key'                => 'brand_color',
                'value'              => '#f7e461',
                'created_at'         => '2018-01-25 05:15:28',
                'updated_at'         => '2018-01-25 05:15:28',
            ],
            [
                'business_id'        => 13,
                'business_option_id' => 9,
                'type'               => 'text',
                'key'                => 'twitter',
                'value'              => 'twitter.com',
                'created_at'         => '2018-01-25 05:15:40',
                'updated_at'         => '2018-01-25 05:15:40',
            ],
            [
                'business_id'        => 13,
                'business_option_id' => 9,
                'type'               => 'text',
                'key'                => 'facebook',
                'value'              => 'facebook.com',
                'created_at'         => '2018-01-25 05:15:40',
                'updated_at'         => '2018-01-25 05:15:40',
            ],
            [
                'business_id'        => 13,
                'business_option_id' => 9,
                'type'               => 'text',
                'key'                => 'instagram',
                'value'              => 'instagram.com',
                'created_at'         => '2018-01-25 05:15:40',
                'updated_at'         => '2018-01-25 05:15:40',
            ],
            [
                'business_id'        => 13,
                'business_option_id' => 10,
                'type'               => 'text',
                'key'                => 'financing_option',
                'value'              => 'yes',
                'created_at'         => '2018-01-25 05:15:48',
                'updated_at'         => '2018-01-25 05:15:48',
            ],
            [
                'business_id'        => 13,
                'business_option_id' => 11,
                'type'               => 'text',
                'key'                => 'initial_accounting_software',
                'value'              => 'yes',
                'created_at'         => '2018-01-25 05:15:54',
                'updated_at'         => '2018-01-25 05:15:54',
            ],
            [
                'business_id'        => 13,
                'business_option_id' => 12,
                'type'               => 'text',
                'key'                => 'business_banking',
                'value'              => 'yes',
                'created_at'         => '2018-01-25 05:16:00',
                'updated_at'         => '2018-01-25 05:16:00',
            ],
            [
                'business_id'        => 13,
                'business_option_id' => 13,
                'type'               => 'text',
                'key'                => 'merchant_facilities',
                'value'              => 'yes',
                'created_at'         => '2018-01-25 05:16:06',
                'updated_at'         => '2018-01-25 05:16:06',
            ],
            [
                'business_id'        => 13,
                'business_option_id' => 14,
                'type'               => 'text',
                'key'                => 'business_email_setup',
                'value'              => 'yes',
                'created_at'         => '2018-01-25 05:16:13',
                'updated_at'         => '2018-01-25 05:16:13',
            ],
            [
                'business_id'        => 13,
                'business_option_id' => 15,
                'type'               => 'text',
                'key'                => 'phone_setup',
                'value'              => 'yes',
                'created_at'         => '2018-01-25 05:16:18',
                'updated_at'         => '2018-01-25 05:16:18',
            ],
            [
                'business_id'        => 13,
                'business_option_id' => 16,
                'type'               => 'text',
                'key'                => 'quick_office_setup',
                'value'              => 'already_have',
                'created_at'         => '2018-01-25 05:16:23',
                'updated_at'         => '2018-01-25 05:16:23',
            ],
            [
                'business_id'        => 13,
                'business_option_id' => 17,
                'type'               => 'text',
                'key'                => 'setup_internet',
                'value'              => 'yes',
                'created_at'         => '2018-01-25 05:16:53',
                'updated_at'         => '2018-01-25 05:16:53',
            ],
            [
                'business_id'        => 14,
                'business_option_id' => 6,
                'type'               => 'file',
                'key'                => 'logo',
                'value'              => 'logo_14_5a69689ea6be8.jpg',
                'created_at'         => '2018-01-25 05:18:22',
                'updated_at'         => '2018-01-25 05:18:22',
            ],
            [
                'business_id'        => 14,
                'business_option_id' => 7,
                'type'               => 'text',
                'key'                => 'tagline',
                'value'              => 'tagline',
                'created_at'         => '2018-01-25 05:18:29',
                'updated_at'         => '2018-01-25 05:18:29',
            ],
            [
                'business_id'        => 14,
                'business_option_id' => 8,
                'type'               => 'text',
                'key'                => 'brand_color',
                'value'              => '#72a951',
                'created_at'         => '2018-01-25 05:18:35',
                'updated_at'         => '2018-01-25 05:18:35',
            ],
            [
                'business_id'        => 14,
                'business_option_id' => 9,
                'type'               => 'text',
                'key'                => 'twitter',
                'value'              => 'facebook.com',
                'created_at'         => '2018-01-25 05:18:44',
                'updated_at'         => '2018-01-25 05:18:44',
            ],
            [
                'business_id'        => 14,
                'business_option_id' => 10,
                'type'               => 'text',
                'key'                => 'financing_option',
                'value'              => 'yes',
                'created_at'         => '2018-01-25 05:18:52',
                'updated_at'         => '2018-01-25 05:18:52',
            ],
            [
                'business_id'        => 14,
                'business_option_id' => 11,
                'type'               => 'text',
                'key'                => 'initial_accounting_software',
                'value'              => 'yes',
                'created_at'         => '2018-01-25 05:18:57',
                'updated_at'         => '2018-01-25 05:18:57',
            ],
            [
                'business_id'        => 14,
                'business_option_id' => 12,
                'type'               => 'text',
                'key'                => 'business_banking',
                'value'              => 'yes',
                'created_at'         => '2018-01-25 05:19:02',
                'updated_at'         => '2018-01-25 05:19:02',
            ],
            [
                'business_id'        => 14,
                'business_option_id' => 13,
                'type'               => 'text',
                'key'                => 'merchant_facilities',
                'value'              => 'yes',
                'created_at'         => '2018-01-25 05:19:08',
                'updated_at'         => '2018-01-25 05:19:08',
            ],
            [
                'business_id'        => 14,
                'business_option_id' => 14,
                'type'               => 'text',
                'key'                => 'business_email_setup',
                'value'              => 'yes',
                'created_at'         => '2018-01-25 05:19:17',
                'updated_at'         => '2018-01-25 05:19:17',
            ],
            [
                'business_id'        => 14,
                'business_option_id' => 15,
                'type'               => 'text',
                'key'                => 'phone_setup',
                'value'              => 'yes',
                'created_at'         => '2018-01-25 05:19:22',
                'updated_at'         => '2018-01-25 05:19:22',
            ],
            [
                'business_id'        => 14,
                'business_option_id' => 16,
                'type'               => 'text',
                'key'                => 'quick_office_setup',
                'value'              => 'already_have',
                'created_at'         => '2018-01-25 05:19:26',
                'updated_at'         => '2018-01-25 05:19:26',
            ],
            [
                'business_id'        => 14,
                'business_option_id' => 17,
                'type'               => 'text',
                'key'                => 'setup_internet',
                'value'              => 'yes',
                'created_at'         => '2018-01-25 05:19:31',
                'updated_at'         => '2018-01-25 05:19:31',
            ],
            [
                'business_id'        => 14,
                'business_option_id' => 18,
                'type'               => 'text',
                'key'                => 'office_accessories',
                'value'              => 'yes',
                'created_at'         => '2018-01-25 05:19:37',
                'updated_at'         => '2018-01-25 05:19:37',
            ],
            [
                'business_id'        => 14,
                'business_option_id' => 19,
                'type'               => 'text',
                'key'                => 'swot',
                'value'              => 'yes',
                'created_at'         => '2018-01-25 05:19:52',
                'updated_at'         => '2018-01-25 05:19:52',
            ],
            [
                'business_id'        => 14,
                'business_option_id' => 20,
                'type'               => 'text',
                'key'                => 'customer_analysis',
                'value'              => 'yes',
                'created_at'         => '2018-01-25 05:19:57',
                'updated_at'         => '2018-01-25 05:19:57',
            ],
            [
                'business_id'        => 14,
                'business_option_id' => 21,
                'type'               => 'text',
                'key'                => 'demographic_events',
                'value'              => 'yes',
                'created_at'         => '2018-01-25 05:20:03',
                'updated_at'         => '2018-01-25 05:20:03',
            ],
            [
                'business_id'        => 14,
                'business_option_id' => 22,
                'type'               => 'text',
                'key'                => 'social_media_execution',
                'value'              => 'yes',
                'created_at'         => '2018-01-25 05:20:10',
                'updated_at'         => '2018-01-25 05:20:10',
            ],
            [
                'business_id'        => 15,
                'business_option_id' => 6,
                'type'               => 'file',
                'key'                => 'logo',
                'value'              => 'logo_15_5a69696364146.jpg',
                'created_at'         => '2018-01-25 05:21:39',
                'updated_at'         => '2018-01-25 05:21:39',
            ],
            [
                'business_id'        => 15,
                'business_option_id' => 7,
                'type'               => 'text',
                'key'                => 'tagline',
                'value'              => 'tagline',
                'created_at'         => '2018-01-25 05:21:46',
                'updated_at'         => '2018-01-25 05:21:46',
            ],
            [
                'business_id'        => 15,
                'business_option_id' => 8,
                'type'               => 'text',
                'key'                => 'brand_color',
                'value'              => '#cde1e0',
                'created_at'         => '2018-01-25 05:21:52',
                'updated_at'         => '2018-01-25 05:21:52',
            ],
            [
                'business_id'        => 15,
                'business_option_id' => 9,
                'type'               => 'text',
                'key'                => 'twitter',
                'value'              => 'twitter.com',
                'created_at'         => '2018-01-25 05:22:01',
                'updated_at'         => '2018-01-25 05:22:01',
            ],
            [
                'business_id'        => 15,
                'business_option_id' => 10,
                'type'               => 'text',
                'key'                => 'financing_option',
                'value'              => 'yes',
                'created_at'         => '2018-01-25 05:22:07',
                'updated_at'         => '2018-01-25 05:22:07',
            ],
            [
                'business_id'        => 15,
                'business_option_id' => 11,
                'type'               => 'text',
                'key'                => 'initial_accounting_software',
                'value'              => 'yes',
                'created_at'         => '2018-01-25 05:22:13',
                'updated_at'         => '2018-01-25 05:22:13',
            ],
            [
                'business_id'        => 15,
                'business_option_id' => 12,
                'type'               => 'text',
                'key'                => 'business_banking',
                'value'              => 'yes',
                'created_at'         => '2018-01-25 05:22:19',
                'updated_at'         => '2018-01-25 05:22:19',
            ],
            [
                'business_id'        => 15,
                'business_option_id' => 13,
                'type'               => 'text',
                'key'                => 'merchant_facilities',
                'value'              => 'yes',
                'created_at'         => '2018-01-25 05:22:25',
                'updated_at'         => '2018-01-25 05:22:25',
            ],
            [
                'business_id'        => 15,
                'business_option_id' => 14,
                'type'               => 'text',
                'key'                => 'business_email_setup',
                'value'              => 'yes',
                'created_at'         => '2018-01-25 05:22:33',
                'updated_at'         => '2018-01-25 05:22:33',
            ],
            [
                'business_id'        => 15,
                'business_option_id' => 15,
                'type'               => 'text',
                'key'                => 'phone_setup',
                'value'              => 'yes',
                'created_at'         => '2018-01-25 05:22:38',
                'updated_at'         => '2018-01-25 05:22:38',
            ],
            [
                'business_id'        => 15,
                'business_option_id' => 16,
                'type'               => 'text',
                'key'                => 'quick_office_setup',
                'value'              => 'already_have',
                'created_at'         => '2018-01-25 05:22:42',
                'updated_at'         => '2018-01-25 05:22:42',
            ],
            [
                'business_id'        => 15,
                'business_option_id' => 17,
                'type'               => 'text',
                'key'                => 'setup_internet',
                'value'              => 'yes',
                'created_at'         => '2018-01-25 05:22:47',
                'updated_at'         => '2018-01-25 05:22:47',
            ],
            [
                'business_id'        => 15,
                'business_option_id' => 18,
                'type'               => 'text',
                'key'                => 'office_accessories',
                'value'              => 'yes',
                'created_at'         => '2018-01-25 05:22:53',
                'updated_at'         => '2018-01-25 05:22:53',
            ],
            [
                'business_id'        => 15,
                'business_option_id' => 19,
                'type'               => 'text',
                'key'                => 'swot',
                'value'              => 'yes',
                'created_at'         => '2018-01-25 05:23:01',
                'updated_at'         => '2018-01-25 05:23:01',
            ],
            [
                'business_id'        => 15,
                'business_option_id' => 20,
                'type'               => 'text',
                'key'                => 'customer_analysis',
                'value'              => 'yes',
                'created_at'         => '2018-01-25 05:23:06',
                'updated_at'         => '2018-01-25 05:23:06',
            ],
            [
                'business_id'        => 15,
                'business_option_id' => 21,
                'type'               => 'text',
                'key'                => 'demographic_events',
                'value'              => 'https://godaddy.com/register',
                'created_at'         => '2018-01-25 05:23:12',
                'updated_at'         => '2018-01-25 05:23:12',
            ],
            [
                'business_id'        => 15,
                'business_option_id' => 22,
                'type'               => 'text',
                'key'                => 'social_media_execution',
                'value'              => 'yes',
                'created_at'         => '2018-01-25 05:23:19',
                'updated_at'         => '2018-01-25 05:23:19',
            ],
            [
                'business_id'        => 15,
                'business_option_id' => 23,
                'type'               => 'text',
                'key'                => 'budget',
                'value'              => 'yes',
                'created_at'         => '2018-01-25 05:23:27',
                'updated_at'         => '2018-01-25 05:23:27',
            ],
            [
                'business_id'        => 15,
                'business_option_id' => 24,
                'type'               => 'text',
                'key'                => 'legal_adviser',
                'value'              => 'yes',
                'created_at'         => '2018-01-25 05:23:38',
                'updated_at'         => '2018-01-25 05:23:38',
            ],
            [
                'business_id'        => 15,
                'business_option_id' => 25,
                'type'               => 'text',
                'key'                => 'employment_contracts_option',
                'value'              => 'yes',
                'created_at'         => '2018-01-25 05:23:45',
                'updated_at'         => '2018-01-25 05:23:45',
            ],
            [
                'business_id'        => 15,
                'business_option_id' => 26,
                'type'               => 'text',
                'key'                => 'award_wages',
                'value'              => 'yes',
                'created_at'         => '2018-01-25 05:23:51',
                'updated_at'         => '2018-01-25 05:23:51',
            ],
            [
                'business_id'        => 15,
                'business_option_id' => 27,
                'type'               => 'text',
                'key'                => 'hr_policy_option',
                'value'              => 'yes',
                'created_at'         => '2018-01-25 05:23:58',
                'updated_at'         => '2018-01-25 05:23:58',
            ],
            [
                'business_id'        => 15,
                'business_option_id' => 28,
                'type'               => 'text',
                'key'                => 'book_keeping_option',
                'value'              => 'yes',
                'created_at'         => '2018-01-25 05:24:06',
                'updated_at'         => '2018-01-25 05:24:06',
            ],
            [
                'business_id'        => 15,
                'business_option_id' => 29,
                'type'               => 'text',
                'key'                => 'cash_flow_forecasting_option',
                'value'              => 'yes',
                'created_at'         => '2018-01-25 05:28:33',
                'updated_at'         => '2018-01-25 05:28:33',
            ],
            [
                'business_id'        => 15,
                'business_option_id' => 30,
                'type'               => 'text',
                'key'                => 'office_space_option',
                'value'              => 'yes',
                'created_at'         => '2018-01-25 05:28:40',
                'updated_at'         => '2018-01-25 05:28:40',
            ],
            [
                'business_id'        => 15,
                'business_option_id' => 31,
                'type'               => 'text',
                'key'                => 'store_lease_option',
                'value'              => 'yes',
                'created_at'         => '2018-01-25 05:28:46',
                'updated_at'         => '2018-01-25 05:28:46',
            ],
        ]);


    }
}