<?php

use Illuminate\Database\Seeder;

class BusinessesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('businesses')->delete();
        
        \DB::table('businesses')->insert(array (
            0 => 
            array (
                'id' => 1,
                'user_id' => 2,
                'business_category_id' => 7,
                'business_name' => 'Sporer, Sauer and Pfeffer',
                'website' => 'http://website.com',
                'abn' => '8039398689919',
                'acn' => '6124753723741',
                'business_email' => 'ray53@example.com',
            'business_mobile' => '(686) 616-6840 x382',
            'business_general_phone' => '(789) 362-5533',
                'address' => '4135 Oma Bridge Suite 750Port Jayme, NY 08441',
                'sell_goods' => NULL,
                'tagline' => NULL,
                'logo' => NULL,
                'brand_color' => NULL,
                'created_at' => '2017-11-22 09:33:17',
                'updated_at' => '2017-11-23 01:14:43',
            ),
            1 => 
            array (
                'id' => 2,
                'user_id' => 3,
                'business_category_id' => 3,
                'business_name' => 'Zemlak and Sons',
                'website' => 'http://website.com',
                'abn' => '1395043490659',
                'acn' => '2298730831263',
                'business_email' => 'oortiz@example.com',
                'business_mobile' => '581.329.1792 x9917',
                'business_general_phone' => '594.232.0170',
                'address' => '59686 Langworth Street Apt. 769Domenicstad, WA 11225-5734',
                'sell_goods' => NULL,
                'tagline' => NULL,
                'logo' => NULL,
                'brand_color' => NULL,
                'created_at' => '2017-11-22 09:33:17',
                'updated_at' => '2017-11-23 01:14:24',
            ),
            2 => 
            array (
                'id' => 3,
                'user_id' => 6,
                'business_category_id' => 7,
                'business_name' => 'Conn, Gottlieb and Armstrong',
                'website' => 'http://website.com',
                'abn' => '0130410251546',
                'acn' => '7740861810129',
                'business_email' => 'cedrick27@example.org',
                'business_mobile' => '498-769-0221 x85792',
                'business_general_phone' => '915-964-3435 x44229',
                'address' => '963 Schoen ForgeTessiechester, NC 11216',
                'sell_goods' => NULL,
                'tagline' => NULL,
                'logo' => NULL,
                'brand_color' => NULL,
                'created_at' => '2017-11-22 09:33:17',
                'updated_at' => '2017-11-23 01:14:12',
            ),
            3 => 
            array (
                'id' => 4,
                'user_id' => 8,
                'business_category_id' => 1,
                'business_name' => 'Ratke-Raynor',
                'website' => 'http://website.com',
                'abn' => '9832664714464',
                'acn' => '7929153944852',
                'business_email' => 'gutkowski.quentin@example.net',
            'business_mobile' => '(512) 628-1550',
            'business_general_phone' => '(386) 686-5260 x7027',
                'address' => '92061 Kiehn TrafficwayMarksside, NV 16566',
                'sell_goods' => NULL,
                'tagline' => NULL,
                'logo' => NULL,
                'brand_color' => NULL,
                'created_at' => '2017-11-22 09:33:17',
                'updated_at' => '2017-11-23 01:13:47',
            ),
            4 => 
            array (
                'id' => 5,
                'user_id' => 7,
                'business_category_id' => 1,
                'business_name' => 'Kuhic and Sons',
                'website' => 'http://website.com',
                'abn' => '7628000398892',
                'acn' => '2086341746386',
                'business_email' => 'luettgen.cade@example.com',
                'business_mobile' => '1-267-550-0346 x1169',
                'business_general_phone' => '1-828-429-4872 x046',
                'address' => '181 Runolfsson Field Apt. 560Rollinville, PA 66505',
                'sell_goods' => NULL,
                'tagline' => NULL,
                'logo' => NULL,
                'brand_color' => NULL,
                'created_at' => '2017-11-22 09:33:17',
                'updated_at' => '2017-11-23 01:13:34',
            ),
            5 => 
            array (
                'id' => 7,
                'user_id' => 10,
                'business_category_id' => 7,
                'business_name' => '',
                'website' => '',
                'abn' => '',
                'acn' => '',
                'business_email' => '',
                'business_mobile' => '',
                'business_general_phone' => '',
                'address' => '',
                'sell_goods' => NULL,
                'tagline' => NULL,
                'logo' => NULL,
                'brand_color' => NULL,
                'created_at' => '2017-11-22 09:33:17',
                'updated_at' => '2017-11-23 01:13:22',
            ),
            6 => 
            array (
                'id' => 8,
                'user_id' => 11,
                'business_category_id' => 1,
                'business_name' => NULL,
                'website' => NULL,
                'abn' => '8888 8888 8888',
                'acn' => NULL,
                'business_email' => NULL,
                'business_mobile' => NULL,
                'business_general_phone' => NULL,
                'address' => NULL,
                'sell_goods' => 1,
                'tagline' => NULL,
                'logo' => NULL,
                'brand_color' => NULL,
                'created_at' => '2018-01-25 05:07:19',
                'updated_at' => '2018-01-25 05:07:19',
            ),
            7 => 
            array (
                'id' => 9,
                'user_id' => 12,
                'business_category_id' => 3,
                'business_name' => 'mybusiness',
                'website' => 'http://mybusiness.com',
                'abn' => '8888 8888 8888',
                'acn' => NULL,
                'business_email' => NULL,
                'business_mobile' => NULL,
                'business_general_phone' => NULL,
                'address' => NULL,
                'sell_goods' => 1,
                'tagline' => NULL,
                'logo' => NULL,
                'brand_color' => NULL,
                'created_at' => '2018-01-25 05:08:12',
                'updated_at' => '2018-01-25 05:09:11',
            ),
            8 => 
            array (
                'id' => 10,
                'user_id' => 13,
                'business_category_id' => 4,
                'business_name' => NULL,
                'website' => NULL,
                'abn' => '8888 8888 8888',
                'acn' => NULL,
                'business_email' => NULL,
                'business_mobile' => NULL,
                'business_general_phone' => NULL,
                'address' => NULL,
                'sell_goods' => 1,
                'tagline' => NULL,
                'logo' => NULL,
                'brand_color' => NULL,
                'created_at' => '2018-01-25 05:10:28',
                'updated_at' => '2018-01-25 05:10:28',
            ),
            9 => 
            array (
                'id' => 11,
                'user_id' => 14,
                'business_category_id' => 1,
                'business_name' => 'mybusinessname',
                'website' => 'http://lksdfjsld.com',
                'abn' => '8888 8888 8888',
                'acn' => NULL,
                'business_email' => NULL,
                'business_mobile' => NULL,
                'business_general_phone' => NULL,
                'address' => NULL,
                'sell_goods' => 0,
                'tagline' => NULL,
                'logo' => NULL,
                'brand_color' => NULL,
                'created_at' => '2018-01-25 05:11:09',
                'updated_at' => '2018-01-25 05:11:22',
            ),
            10 => 
            array (
                'id' => 12,
                'user_id' => 15,
                'business_category_id' => 7,
                'business_name' => 'mubusiness',
                'website' => 'http://mubys.com',
                'abn' => '8888 8888 8888',
                'acn' => NULL,
                'business_email' => NULL,
                'business_mobile' => NULL,
                'business_general_phone' => NULL,
                'address' => NULL,
                'sell_goods' => 1,
                'tagline' => NULL,
                'logo' => NULL,
                'brand_color' => NULL,
                'created_at' => '2018-01-25 05:12:15',
                'updated_at' => '2018-01-25 05:12:42',
            ),
            11 => 
            array (
                'id' => 13,
                'user_id' => 16,
                'business_category_id' => 1,
                'business_name' => 'lvel',
                'website' => 'http://lll.com',
                'abn' => '8888 8888 8888',
                'acn' => NULL,
                'business_email' => NULL,
                'business_mobile' => NULL,
                'business_general_phone' => NULL,
                'address' => NULL,
                'sell_goods' => 1,
                'tagline' => NULL,
                'logo' => NULL,
                'brand_color' => NULL,
                'created_at' => '2018-01-25 05:14:42',
                'updated_at' => '2018-01-25 05:15:01',
            ),
            12 => 
            array (
                'id' => 14,
                'user_id' => 17,
                'business_category_id' => 5,
                'business_name' => 'mybusiness',
                'website' => 'http://muyb.com',
                'abn' => '8888 8888 8888',
                'acn' => NULL,
                'business_email' => NULL,
                'business_mobile' => NULL,
                'business_general_phone' => NULL,
                'address' => NULL,
                'sell_goods' => 0,
                'tagline' => NULL,
                'logo' => NULL,
                'brand_color' => NULL,
                'created_at' => '2018-01-25 05:17:47',
                'updated_at' => '2018-01-25 05:18:11',
            ),
            13 => 
            array (
                'id' => 15,
                'user_id' => 18,
                'business_category_id' => 1,
                'business_name' => 'aslkfd',
                'website' => 'http://lskdjfsdl.com',
                'abn' => '9999 9999 9999',
                'acn' => NULL,
                'business_email' => NULL,
                'business_mobile' => NULL,
                'business_general_phone' => NULL,
                'address' => NULL,
                'sell_goods' => 0,
                'tagline' => NULL,
                'logo' => NULL,
                'brand_color' => NULL,
                'created_at' => '2018-01-25 05:21:00',
                'updated_at' => '2018-01-25 05:21:20',
            ),
        ));
        
        
    }
}