<?php

use Illuminate\Database\Seeder;

class BusinessOptionsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('business_options')->delete();
        
        \DB::table('business_options')->insert(array (
            0 => 
            array (
                'id' => 1,
                'level_id' => 1,
                'section_id' => 1,
                'parent_id' => NULL,
                'name' => 'What industry is your business idea in?',
                'slug' => 'what-industry-is-your-business-idea-in',
                'description' => NULL,
                'content' => 'Select the best fit below. Don\'t worry you can always change your selection later.',
                'element' => 'BusinessCategories',
                'tooltip' => NULL,
                'menu_order' => 1,
                'weight' => 1,
                'show_everywhere' => 1,
                'created_at' => NULL,
                'updated_at' => '2018-01-07 10:48:14',
            ),
            1 => 
            array (
                'id' => 2,
                'level_id' => 1,
                'section_id' => 1,
                'parent_id' => NULL,
                'name' => 'Will you also be selling goods online?',
                'slug' => 'will-you-also-be-selling-goods-online',
                'description' => NULL,
                'content' => NULL,
                'element' => 'SellGoods',
                'tooltip' => NULL,
                'menu_order' => 2,
                'weight' => 1,
                'show_everywhere' => 0,
                'created_at' => '2018-01-07 10:43:38',
                'updated_at' => '2018-01-07 10:43:38',
            ),
            2 => 
            array (
                'id' => 3,
                'level_id' => 1,
                'section_id' => 2,
                'parent_id' => NULL,
                'name' => 'Great Now lets create your account',
                'slug' => 'great-now-lets-create-your-account',
                'description' => NULL,
                'content' => NULL,
                'element' => 'RegisterUser',
                'tooltip' => 'create account',
                'menu_order' => 3,
                'weight' => 1,
                'show_everywhere' => 1,
                'created_at' => '2017-11-23 01:28:17',
                'updated_at' => '2018-01-07 10:50:06',
            ),
            3 => 
            array (
                'id' => 4,
                'level_id' => 1,
                'section_id' => 3,
                'parent_id' => NULL,
                'name' => 'So tell us about your business',
                'slug' => 'so-tell-us-about-your-business',
                'description' => 'What name have you decided for your business? Are you stuck in choosing a name - click here for a few tips.',
                'content' => NULL,
                'element' => 'CreateBusiness',
                'tooltip' => 'What name have you decided for your business? Are you stuck in choosing a name - click here for a few tips.',
                'menu_order' => 4,
                'weight' => 1,
                'show_everywhere' => 1,
                'created_at' => '2017-11-23 01:29:09',
                'updated_at' => '2018-01-07 10:52:07',
            ),
            4 => 
            array (
                'id' => 5,
                'level_id' => 1,
                'section_id' => 4,
                'parent_id' => NULL,
                'name' => 'Register Your Business',
                'slug' => 'register-your-business',
                'description' => NULL,
                'content' => NULL,
                'element' => 'RegisterBusiness',
                'tooltip' => 'If you’re unsure as to the best options to choose in this section you use an additional service from X to guide you through this step or call the Australian Government helpline',
                'menu_order' => 5,
                'weight' => 1,
                'show_everywhere' => 1,
                'created_at' => '2017-11-23 01:30:17',
                'updated_at' => '2018-01-07 10:53:32',
            ),
            5 => 
            array (
                'id' => 6,
                'level_id' => 2,
                'section_id' => 5,
                'parent_id' => NULL,
                'name' => 'Do you have a logo',
                'slug' => 'do-you-have-a-logo',
                'description' => NULL,
                'content' => 'logo upload shortcode',
                'element' => NULL,
                'tooltip' => 'marketing',
                'menu_order' => 6,
                'weight' => 1,
                'show_everywhere' => 1,
                'created_at' => '2017-11-23 01:49:28',
                'updated_at' => '2018-01-09 19:11:42',
            ),
            6 => 
            array (
                'id' => 7,
                'level_id' => 2,
                'section_id' => 5,
                'parent_id' => 12,
                'name' => 'Select Your Brand Color',
                'slug' => 'select-your-brand-color',
                'description' => NULL,
                'content' => 'shortcode brand color',
                'element' => NULL,
                'tooltip' => 'brand color',
                'menu_order' => 7,
                'weight' => 1,
                'show_everywhere' => 1,
                'created_at' => '2017-11-23 01:51:54',
                'updated_at' => '2018-01-09 19:12:26',
            ),
            7 => 
            array (
                'id' => 8,
                'level_id' => 2,
                'section_id' => 5,
                'parent_id' => 13,
                'name' => 'Social Media Registration',
                'slug' => 'social-media-registration',
                'description' => NULL,
                'content' => 'social media registration shortcode',
                'element' => NULL,
                'tooltip' => 'social',
                'menu_order' => 8,
                'weight' => 1,
                'show_everywhere' => 1,
                'created_at' => '2017-11-23 01:52:43',
                'updated_at' => '2018-01-09 19:12:43',
            ),
            8 => 
            array (
                'id' => 9,
                'level_id' => 2,
                'section_id' => 6,
                'parent_id' => NULL,
                'name' => 'How you set up your business email address?',
                'slug' => 'finance-option',
                'description' => NULL,
                'content' => NULL,
                'element' => NULL,
                'tooltip' => 'How you set up your business email address?',
                'menu_order' => 9,
                'weight' => 1,
                'show_everywhere' => 1,
                'created_at' => '2017-11-23 01:55:03',
                'updated_at' => '2018-01-07 11:01:58',
            ),
            9 => 
            array (
                'id' => 10,
                'level_id' => 2,
                'section_id' => 6,
                'parent_id' => NULL,
                'name' => 'Merchant Facilities',
                'slug' => 'merchant-facilities',
                'description' => NULL,
                'content' => 'yet to decide',
                'element' => NULL,
                'tooltip' => 'merchant facilities',
                'menu_order' => 10,
                'weight' => 1,
                'show_everywhere' => 1,
                'created_at' => '2017-11-23 01:56:30',
                'updated_at' => '2018-01-09 19:12:01',
            ),
            10 => 
            array (
                'id' => 11,
                'level_id' => 2,
                'section_id' => 7,
                'parent_id' => NULL,
                'name' => 'Financing Option?',
                'slug' => 'which-area-of-your-business-would-you-like-to-work-on-first',
                'description' => NULL,
                'content' => NULL,
                'element' => NULL,
                'tooltip' => 'Choose category',
                'menu_order' => 11,
                'weight' => 1,
                'show_everywhere' => 1,
                'created_at' => '2017-11-23 01:46:02',
                'updated_at' => '2018-01-07 10:56:46',
            ),
            11 => 
            array (
                'id' => 12,
                'level_id' => 2,
                'section_id' => 7,
                'parent_id' => NULL,
                'name' => 'Which area of your business would you like to work on first?',
                'slug' => 'which-area-of-your-business-would-you-like-to-work-on-first',
                'description' => NULL,
                'content' => 'shortcode to show business options',
                'element' => NULL,
                'tooltip' => 'starting',
                'menu_order' => 12,
                'weight' => 1,
                'show_everywhere' => 1,
                'created_at' => '2017-11-23 01:57:34',
                'updated_at' => '2018-01-09 19:12:18',
            ),
            12 => 
            array (
                'id' => 13,
                'level_id' => 3,
                'section_id' => 8,
                'parent_id' => NULL,
                'name' => 'SWOT',
                'slug' => 'swot',
                'description' => NULL,
                'content' => NULL,
                'element' => NULL,
                'tooltip' => 'SWOT?',
                'menu_order' => 13,
                'weight' => 1,
                'show_everywhere' => 1,
                'created_at' => '2017-11-23 02:04:19',
                'updated_at' => '2018-01-07 11:04:49',
            ),
            13 => 
            array (
                'id' => 14,
                'level_id' => 3,
                'section_id' => 9,
                'parent_id' => NULL,
                'name' => 'Have you kept a legal advisor?',
                'slug' => 'have-you-kept-a-legal-advisor',
                'description' => NULL,
                'content' => NULL,
                'element' => NULL,
                'tooltip' => 'legal advisor',
                'menu_order' => 14,
                'weight' => 1,
                'show_everywhere' => 1,
                'created_at' => '2018-01-07 11:07:02',
                'updated_at' => '2018-01-09 19:14:06',
            ),
            14 => 
            array (
                'id' => 15,
                'level_id' => 3,
                'section_id' => 10,
                'parent_id' => NULL,
                'name' => 'Do you have employment contracts already?',
                'slug' => 'do-you-have-employment-contracts-already',
                'description' => NULL,
                'content' => NULL,
                'element' => NULL,
                'tooltip' => 'Do you have employment contracts already?',
                'menu_order' => 15,
                'weight' => 1,
                'show_everywhere' => 1,
                'created_at' => '2018-01-07 11:03:57',
                'updated_at' => '2018-01-09 19:13:54',
            ),
            15 => 
            array (
                'id' => 16,
                'level_id' => 3,
                'section_id' => 11,
                'parent_id' => NULL,
                'name' => 'Office space?',
                'slug' => 'office-space',
                'description' => NULL,
                'content' => NULL,
                'element' => NULL,
                'tooltip' => 'Office space?',
                'menu_order' => 16,
                'weight' => 1,
                'show_everywhere' => 1,
                'created_at' => '2018-01-07 11:05:23',
                'updated_at' => '2018-01-09 19:14:17',
            ),
            16 => 
            array (
                'id' => 17,
                'level_id' => 3,
                'section_id' => 12,
                'parent_id' => NULL,
                'name' => 'Book keeping?',
                'slug' => 'book-keeping',
                'description' => NULL,
                'content' => NULL,
                'element' => NULL,
                'tooltip' => 'Book keeping?',
                'menu_order' => 19,
                'weight' => 1,
                'show_everywhere' => 1,
                'created_at' => '2018-01-07 11:03:22',
                'updated_at' => '2018-01-09 19:14:29',
            ),
        ));
        
        
    }
}